# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-11 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_rank', models.IntegerField(choices=[(1, '\u4e00\u7ea7\u677f\u5757'), (2, '\u4e8c\u7ea7\u677f\u5757'), (3, '\u4e09\u7ea7\u677f\u5757')], default=1)),
                ('url', models.URLField(max_length=50)),
                ('title', models.CharField(max_length=256, null=True)),
                ('content', models.TextField(null=True)),
                ('signature', models.CharField(blank=True, max_length=30, null=True)),
                ('source', models.CharField(max_length=30)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('acthor', models.CharField(max_length=10)),
                ('auditor', models.CharField(max_length=10)),
                ('commentable', models.IntegerField(default=0)),
                ('hit', models.IntegerField(default=0)),
                ('isAvailable', models.BooleanField(default=False)),
                ('isTop', models.BooleanField(default=False)),
                ('isLink', models.BooleanField(default=False)),
                ('isEmergency', models.BooleanField(default=False)),
                ('isHot', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'news_information',
            },
        ),
    ]
